### ISSUE TITLE
`datasummary_balance()`: Inconsistent LaTeX column nesting with "latex" vs "latex_tabular" output

### ISSUE THREAD

**Issue by acarril** [vincentarelbundock/modelsummary#719]
Thank you for the amazing package!

# 1. Bug description

`datasummary_balance()` has inconsistent behavior on column titles/grouping for different LaTeX outputs. Using `output = "latex"` nests the summary statistics under `multicolumn` group labels, but using `output = "latex_tabular"` does not nest them. I would expect this behavior to be consistent across these two option values.

# 2. Minimal reproducible example

**Setup:**
```r
library(modelsummary)
library(estimatr)
library(dplyr)
library(magrittr)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/Ecdat/Treatment.csv'
training <- read.csv(url, na.strings = "")
```

- Creating a balance table with the `output = "latex"` option produces a LaTeX table which nests the summary statistics under the values of the grouping variable (in `multicolumn`), as expected. 
```r
r$> datasummary_balance(~treat, data = training, output = "latex")

# Output:
\begin{tabular}[t]{llrrrrrr}
\toprule
\multicolumn{2}{c}{ } & \multicolumn{2}{c}{FALSE (N=2490)} & \multicolumn{2}{c}{TRUE (N=185)} & \multicolumn{2}{c}{ } \\
\cmidrule(l{3pt}r{3pt}){3-4} \cmidrule(l{3pt}r{3pt}){5-6}
  &    & Mean & Std. Dev. & Mean & Std. Dev. & Diff. in Means & Std. Error\\
\midrule
rownames &  & 1430.5 & 718.9 & 93.0 & 53.5 & -1337.5 & 14.9\\
age &  & 34.9 & 10.4 & 25.8 & 7.2 & -9.0 & 0.6\\
# ...
\end{tabular}
```
<img width="734" alt="image" src="https://github.com/vincentarelbundock/modelsummary/assets/9773292/1559048d-268d-42b0-9016-47a2c8f3226f">

- Creating the same balance table with `output = "latex_tabular"` does not nest the summary statistics across a common group value.
```r
r$> datasummary_balance(~treat, data = training, output = "latex_tabular")

# Output:
\begin{tabular}[t]{llrrrrrr}
\toprule
  &    & FALSE (N=2490) / Mean & FALSE (N=2490) / Std. Dev. & TRUE (N=185) / Mean & TRUE (N=185) / Std. Dev. & Diff. in Means & Std. Error\\
\midrule
rownames &  & 1430.5 & 718.9 & 93.0 & 53.5 & -1337.5 & 14.9\\
age &  & 34.9 & 10.4 & 25.8 & 7.2 & -9.0 & 0.6\\
# ...
\end{tabular}
```
<img width="833" alt="image" src="https://github.com/vincentarelbundock/modelsummary/assets/9773292/a2152b5d-9039-4714-a2b3-4e225c932c9a">

# 3. Session Info

```txt
R version 4.2.3 Patched (2023-04-13 r84396)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.6.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] magrittr_2.0.3     dplyr_1.1.4        estimatr_1.0.2     modelsummary_1.4.5

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.12       pillar_1.9.0      compiler_4.2.3    tools_4.2.3       digest_0.6.34
 [6] viridisLite_0.4.2 evaluate_0.23     lifecycle_1.0.4   tibble_3.2.1      checkmate_2.3.1
[11] pkgconfig_2.0.3   rlang_1.1.3       cli_3.6.2         rstudioapi_0.15.0 xfun_0.42
[16] fastmap_1.1.1     kableExtra_1.4.0  xml2_1.3.6        stringr_1.5.1     knitr_1.45
[21] generics_0.1.3    vctrs_0.6.5       systemfonts_1.0.6 tidyselect_1.2.0  svglite_2.1.3
[26] glue_1.7.0        R6_2.5.1          fansi_1.0.6       rmarkdown_2.26    Formula_1.2-5
[31] tables_0.9.17     backports_1.4.1   scales_1.3.0      htmltools_0.5.7   insight_0.19.8
[36] colorspace_2.1-0  utf8_1.2.4        stringi_1.8.3     munsell_0.5.0
```

**Comment by vincentarelbundock** [comment]
Thanks for the report! I confirm that this issue occurs on my computer too and that we need to fix this.

I plan to make one further improvement to `tinytable` which should resolve this semi-automatically. So let's not attempt anything now. Hopefully this fixes itself in the next few days.

**Comment by vincentarelbundock** [comment]
Thanks again fro the report. Should now be fixed, but it requires the development versions of both `modelsummary` and `tinytable`, as well as the `tabularray` package loaded in the LaTeX preamble.

**Comment by kmfrick** [comment]
This still happens if you use kable with `output = "latex"`!

**Comment by kmfrick** [comment]
Yes I was using tinytable, but I noticed this happening when I switched to kableExtra for compatibility with older code and forgot to switch back. I'll see if I can trace this and submit a PR. Thanks!

**Comment by vincentarelbundock** [comment]
Thanks!
